.gitignore
Just what it says on the tin. test.ini came along for the ride (modeled after ignore in mff_rams_plugin)
=> Added dev ini to gitignore

art_show/model_checks.py
=> Added minimum value checks

art_show/templates/art_show_applications/confirmation.html
=> Made email clickable

art_show/templates/emails/art_show/declined.txt
No ticket filed for this bug, it was just something I noticed in the logs that hadn't been fixed.
=> Removed inappropriate endif

art_show/models.py, art_show/templates/art_show_applications/art_show_form.html, art_show/templates/emails/art_show/appchange_notification.html, art_show/templates/emails/art_show/application.html, art_show/templates/emails/art_show/approved.html, art_show/templates/emails/art_show/declined.txt
Merge the latest staging changes, all reviewed into master
Fixes #49, #47, #40, #35, #37, #38, #41, #42
=> Mff staging

art_show/__init__.py, art_show/configspec.ini, art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/sales_charge_form.html
Based on the arbitrary charge form in the main plugin, with some improvements.
=> Add a sales charge form for art show which calculates sales tax

alembic/versions/af64b33e950a_initial_migration.py, art_show/__init__.py, art_show/automated_emails.py, art_show/config.py, art_show/configspec.ini, art_show/model_checks.py, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/site_sections/art_show_applications.py, art_show/templates/art_show_admin/form.html, art_show/templates/art_show_admin/history.html, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_admin/sales_charge_form.html, art_show/templates/art_show_applications/art_show_form.html, tox.ini
Also adds the basic art show fields for 2018.
=> Update art show plugin to work with Uber 2018

art_show/models.py, art_show/site_sections/art_show_applications.py, art_show/templates/art_show_applications/edit.html
Now with 100% fewer merge errors!
=> Collect address for non-attending artists mailing in art

art_show/templates/art_show_applications/confirmation.html
=> Removed bad ref to fixing email in application

alembic/versions/e1d3c11eb9dd_add_adult_panels_and_tables.py, art_show/models.py, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_applications/art_show_form.html, art_show/templates/art_show_applications/confirmation.html, art_show/templates/emails/art_show/appchange_notification.html, art_show/templates/emails/art_show/application.html, art_show/templates/emails/art_show/approved.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/66. The most basic implementation -- we're effectively just copying the regular panels and table sections.
=> Add 'adult' table sections and panels

art_show/templates/emails/art_show/payment_confirmation.txt
Just what it says on the tin. Fixes #78
=> Added adult resources and mailing fee

art_show/templates/emails/art_show/appchange_notification.html, art_show/templates/emails/art_show/approved.html
Fixing something Trish's testing noted wrt agent codes in emails
=> Add agent codes to appropriate emails

art_show/templates/art_show_admin/index.html
=> Fixed admin notes to show from app, not attendee

art_show/model_checks.py, art_show/templates/art_show_applications/art_show_form.html
Per @hugmonster the website field should be mandatory. Now it is.
fixes #85
=> Made website mandatory

art_show/site_sections/art_show_applications.py
Fixes https://github.com/MidwestFurryFandom/art_show/issues/87
=> Update art show total price before app change notification

art_show/model_checks.py
Fixes https://github.com/MidwestFurryFandom/art_show/issues/90
=> Let applicants apply for only mature panels/tables

art_show/templates/art_show_applications/art_show_form.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/93.
=> Only show agent code on app if artist is actually using an agent

art_show/models.py, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_applications/edit.html
Helps admins track the status of art applications. Fixes https://github.com/MidwestFurryFandom/art_show/issues/83. Fixes https://github.com/MidwestFurryFandom/art_show/issues/95.
=> Add incomplete reason

art_show/templates/art_show_admin/index.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/74 by adding the artist's name, if it exists, after their full name.
=> Add Artist Name to admin overview

alembic/versions/6fd0a683af2d_add_more_art_show_app_fields.py, alembic/versions/f812bc84e064_add_art_show_piece_table.py, art_show/configspec.ini, art_show/model_checks.py, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/site_sections/art_show_applications.py, art_show/templates/art_pieces_form.html, art_show/templates/art_show_admin/form.html, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_admin/pieces.html, art_show/templates/art_show_applications/art_pieces_form.html, art_show/templates/art_show_applications/edit.html, art_show/templates/emails/art_show/appchange_notification.html, art_show/templates/emails/art_show/pieces_confirmation.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/107 and all related issues. Depends on https://github.com/MidwestFurryFandom/rams/pull/264.
=> Add ability for artists to submit Art Show Pieces

art_show/templates/art_show_admin/index.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/113. Depends on https://github.com/MidwestFurryFandom/rams/pull/261.
Looks like this:
=> Add approval and payment filters to Art Show applications page

art_show/model_checks.py, art_show/templates/art_pieces_form.html, art_show/templates/emails/art_show/approved.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/127. Fixes https://github.com/MidwestFurryFandom/art_show/issues/128. Fixes https://github.com/MidwestFurryFandom/art_show/issues/129.
=> Implement Art Show feedback for Addendum 5

art_show/configspec.ini, art_show/model_checks.py, art_show/templates/art_pieces_form.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/132. Depends on https://github.com/MidwestFurryFandom/rams/pull/274.
=> Limit length of piece name and media

art_show/models.py
It'd be nice to get this in before we deploy to prod.
=> Stop changing the artist ID constantly

art_show/templates/art_show_admin/index.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/103.
=> Add Delivery Method to admin overview

alembic/versions/14ef3a47a1d6_add_address_fields_to_art_show_apps.py, alembic/versions/5481f9d61d81_add_checked_in_and_location_columns_to_.py, art_show/config.py, art_show/model_checks.py, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/site_sections/art_show_applications.py, art_show/templates/art_pieces_form.html, art_show/templates/art_show_admin/ops.html, art_show/templates/art_show_applications/art_show_form.html, art_show/templates/art_show_applications/edit.html, art_show/templates/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/105, though not all of its sub-issues. Fixes https://github.com/MidwestFurryFandom/art_show/issues/106. Fixes https://github.com/MidwestFurryFandom/art_show/issues/123. Requires https://github.com/MidwestFurryFandom/rams/pull/276.
=> Add Ops page and check-in functionality

art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/ops.html, art_show/templates/art_show_applications/art_show_form.html, art_show/templates/artist_checkin_macros.html
Bypasses fiddling with the international checkbox and simply sets the correct value in the page handler. Fixes https://github.com/MidwestFurryFandom/art_show/issues/141.
=> Remove 'international' checkbox from artist checkin form

art_show/templates/art_show_admin/ops.html, art_show/templates/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/146. We were using jQuery to add or remove a value from a field based on which submit button was clicked, but it wasn't working because we had multiple fields with the same ID. Once again I have no idea how this worked before.
=> Fix jQuery error preventing check-in form from updating properly

art_show/site_sections/art_show_admin.py, art_show/templates/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/150.
=> Correctly handle $0 prices during artist check-in

alembic/versions/54227ab70c17_add_bidder_signup.py, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/artist_check_in_out.html, art_show/templates/art_show_admin/bidder_signup.html, art_show/templates/art_show_admin/ops.html, art_show/templates/art_show_admin/print_bidder_form.html, art_show/templates/artist_checkin_macros.html, art_show/templates/bidder_signup_macros.html, art_show/templates/print_form.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/119.
This page can be accessed via the At Con Operations page.
=> Add bidder signup page

art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/form.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/48.
=> Add explicit payment controls to art show apps

art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/pieces_bought.html, art_show/templates/art_show_admin/print_receipt.html, art_show/templates/art_show_admin/sales_search.html
This includes a 500 error preventing access to the sales search page. ...whoops.
=> Fix errors found in sales workflow

art_show/site_sections/art_show_admin.py
Admins could not make an art show app with an existing attendee because the dropdown box was wrong. The new app_paid feature also just broke the entire page. This fixes both things.
=> Make creating an art show app from the admin side actually work

alembic/versions/df889f662fe6_add_paypal_address_column_for_.py, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/artist_check_in_out.html, art_show/templates/art_show_admin/close_out.html, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_admin/print_check_in_out_form.html, art_show/templates/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/191. Fixes https://github.com/MidwestFurryFandom/art_show/issues/192. Fixes https://github.com/MidwestFurryFandom/art_show/issues/193.
=> Implement Art Show Close-Out Feedback

art_show/site_sections/art_show_reports.py, art_show/templates/art_show_reports/index.html, art_show/templates/art_show_reports/pieces_by_status.html, art_show/templates/art_show_reports/sales_invoices.html, art_show/templates/print_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/168
=> Add a pieces report that can be filtered by status

art_show/models.py, art_show/site_sections/art_show_reports.py, art_show/templates/art_show_reports/high_bids.html, art_show/templates/art_show_reports/index.html, art_show/templates/art_show_reports/pieces_by_status.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/169.
=> Add high bids report for printing out after close-out

art_show/site_sections/art_show_reports.py, art_show/templates/art_show_reports/auction_report.html, art_show/templates/art_show_reports/index.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/170. Fixes https://github.com/MidwestFurryFandom/art_show/issues/171.
There will almost certainly be a merge conflict with https://github.com/MidwestFurryFandom/art_show/pull/206, since I had to use the same import line to get the current time.
=> Add Auction Report for Mature and General Galleries

art_show/site_sections/art_show_reports.py, art_show/templates/art_show_reports/index.html, art_show/templates/art_show_reports/summary.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/172.
=> Add Grand Summary Report

art_show/site_sections/art_show_admin.py
Fixes https://github.com/MidwestFurryFandom/art_show/issues/153.
=> Use artist name and current time in bidsheet PDF

alembic/versions/fc49b3e7cc91_add_tracking_for_pieces_that_went_to_.py, art_show/configspec.ini, art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/site_sections/art_show_applications.py, art_show/site_sections/art_show_reports.py, art_show/templates/art_pieces_form.html, art_show/templates/art_show_admin/artist_check_in_out.html, art_show/templates/art_show_admin/index.html, art_show/templates/art_show_admin/print_artist_invoice.html, art_show/templates/art_show_reports/artist_invoices.html, art_show/templates/art_show_reports/index.html, art_show/templates/art_show_reports/summary.html, art_show/templates/artist_checkin_macros.html, art_show/templates/emails/art_show/appchange_notification.html, art_show/templates/print_form.html, art_show/templates/print_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/173. We also now have the commission fee in configuration, and we track whether a piece has ever been to auction.
This commit requires `/app/sideboard/sep.py alembic upgrade heads` to be run in the web container.
=> Add artist payout invoices

art_show/site_sections/art_show_reports.py, art_show/templates/art_show_reports/high_bids.html, art_show/templates/art_show_reports/index.html
You get a CSV export, and you get a CSV export. Everyone gets CSV exports!
=> Add Art Show CSV reports

art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/artist_check_in_out.html, art_show/templates/art_show_admin/bidder_signup.html, art_show/templates/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/215.
=> Improve Artist Check-in/out

art_show/models.py
We think this may be preventing the server from starting correctly.
=> Stop importing Session twice

.gitignore, art_show/model_checks.py, art_show/templates/art_show_applications/art_show_form.html, art_show/templates/art_show_applications/edit.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/243. Also fixes a couple other minor bugs I found while testing.
=> Only check duplicate names against the same artist

art_show/model_checks.py, art_show/models.py
Fixes https://github.com/MidwestFurryFandom/art_show/issues/246.
=> Stop artists selecting galleries they aren't in

art_show/site_sections/art_show_admin.py, art_show/templates/art_show_admin/assign_locations.html, art_show/templates/art_show_admin/ops.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/242.
=> Add location assignment page

art_show/templates/art_show_admin/artist_check_in_out.html, art_show/templates/art_show_admin/bidder_signup.html, art_show/templates/art_show_admin/sales_search.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/234. I found some extra pages with broken pagination, so this also fixes those.
=> Make pagination links actually work

art_show/templates/emails/art_show/pieces_reminder.txt
=> Updated art show reminder, #264

art_show/model_checks.py, art_show/models.py
We refactored `attendee_from_art_show_app` into a more generic function so we could also use it for our Marketplace apps, so we ought to use it.
=> Use create_or_find_attendee_by_id for art show apps

art_show/models.py, art_show/site_sections/art_show_admin.py, art_show/site_sections/art_show_applications.py, art_show/templates/art_pieces_form.html, art_show/templates/art_show_admin/pieces_bought.html, art_show/templates/art_show_reports/auction_report.html, art_show/templates/art_show_reports/high_bids.html, art_show/templates/art_show_reports/pieces_by_status.html, art_show/templates/artist_checkin_macros.html, art_show/templates/emails/art_show/pieces_confirmation.html, art_show/templates/print_macros.html
Fixes a bunch of bugs that showed up in our art show plugin after I made some changes. Also includes a new fix to handle very long words in piece names, which Trish noticed while testing for other bugs.
=> Fix art show regression bugs

art_show/automated_emails.py, art_show/templates/emails/art_show/mailing_in.html
Fixes https://github.com/MidwestFurryFandom/art_show/issues/240.
=> Add email with mail-in instructions
