MidwestFurryFandom/art_show

art_show/site_sections/art_show_applications.py

Fixes https://github.com/MidwestFurryFandom/art_show/issues/12. We needed an extra flag in the send_email function call.

Render art show application confirmation email as HTML

---

art_show/templates/art_show_applications/art_show_form.html
art_show/templates/art_show_applications/edit.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/14 by disabling fields instead of making them readonly. Since there's no point in the applicant submitting the form after it's been reviewed, we also hide the submit button.

Disable all fields and hide submit button for unapproved apps

---

art_show/automated_emails.py

Art show emails now send from the correct address and the payment reminder sends at the correct time (or at least not right away).
Fixes #34 and #35

Art show email sending behavior fixes

---

art_show/templates/art_show_applications/art_show_form.html
art_show/templates/emails/art_show/appchange_notification.html
art_show/templates/emails/art_show/application.html
art_show/templates/emails/art_show/approved.html

All attendee-facing references to "tables" now "Table sections" to better clarify that they are not getting a whole table. This was requested by art show staff.
fixes #37

Updated attendee-facing wording to table sections

---

art_show/templates/art_show_applications/art_show_form.html

Should now show the correct number of panels w/ an informative message if greater than what attendee could select.
Fixes #42

Fix too many panels

---

alembic/versions/1f862611ba04_make_sure_agents_are_attendees.py
art_show/configspec.ini
art_show/model_checks.py
art_show/models.py
art_show/site_sections/art_show_applications.py
art_show/templates/art_show_agent.html
art_show/templates/art_show_applications/art_show_form.html
art_show/templates/art_show_applications/edit.html
art_show/templates/emails/art_show/agent_code.html
art_show/templates/emails/art_show/agent_removed.html
art_show/templates/emails/art_show/appchange_notification.html
art_show/templates/emails/art_show/application.html
art_show/templates/emails/art_show/approved.html
art_show/templates/emails/art_show/declined.txt
art_show/templates/preregistration/confirm.html
art_show/templates/regextra.html

Art show applicants now receive a code to pass onto agents, who may then enter it during pre-reg or on their confirmation page. We overload promo codes to do the former, since it's actually super tricky to do anything to other models during pre-reg.

Add workflow for assigning and unassigning agents to art show apps

---

art_show/models.py
art_show/site_sections/art_show_applications.py
art_show/templates/art_show_link.html

Our model structure changed and we missed a few spots. This was specifically causing a 500 error when checking confirmation numbers for new art apps.

Fix all references to art show application, singular

---

art_show/config.py
art_show/configspec.ini
art_show/site_sections/art_show_applications.py
art_show/templates/static_views/art_show_closed.html
art_show/templates/static_views/art_show_not_open.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/68. We check to see if art show registration is actually open before showing attendees the form.

Add art_show_reg_start

---

art_show/automated_emails.py
art_show/models.py
art_show/site_sections/art_show_applications.py
art_show/templates/emails/art_show/application.html
art_show/templates/emails/art_show/payment_notification.txt
art_show/templates/emails/art_show/reg_notification.txt

We were sending this email with the send_email function, but that meant it was getting sent before we generated the agent code. Automated emails are better anyway. Fixes https://github.com/MidwestFurryFandom/art_show/issues/65.

Change art show app confirmation into an automated email

---

art_show/site_sections/art_show_applications.py
art_show/templates/art_show_admin/form.html

The "Assign New Agent" button was appearing on the admin page, but it wasn't actually hooked up to anything! Fixes https://github.com/MidwestFurryFandom/art_show/issues/96.

Let admins reset artist's agent codes

---

art_show/site_sections/art_show_applications.py

Not strictly necessary to fix https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/76 but we might as well be consistent.

Use from:c.ADMIN_EMAIL for emails to departments

---

art_show/templates/art_pieces_form.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/131, and also fixes the same problem for the no_quick_sale property, by including a hidden field in the status form if applicable.

Stop resetting for_sale and no_quick_sale when updating status

---

art_show/configspec.ini
art_show/models.py
art_show/site_sections/art_show_applications.py
art_show/templates/art_show_admin/form.html
art_show/templates/art_show_admin/index.html
art_show/templates/art_show_applications/edit.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/101 by using the workflow we say we use.
After this PR is merged and deployed, we should run `/app/env/bin/python3 /app/sideboard/sep.py resave_all_attendees_and_groups` inside our web container. This will update all the apps to have the correct payment status as far as the system can tell.

Redirect unpaid artists to art show payment page

---

art_show/templates/art_show_admin/index.html

... Bootstrap.
Fixes https://github.com/MidwestFurryFandom/art_show/issues/116 by removing arbitrary column sizes. Any further shenanigans with the inputs stacking are up to Bootstrap.

Use pull-right class instead of col divs

---

art_show/site_sections/art_show_admin.py

I have no idea how this worked before when I was testing the feature, but it's fixed now!

Fix 500 error on printing bid sheets

---

art_show/templates/emails/art_show/payment_reminder.txt

Missed a spot for |datetime_local.

Fix date display in payment reminder email

---

alembic/versions/181ceea98b62_add_art_show_sales_tables.py
alembic/versions/676530c66ee7_add_buyers_for_pieces_and_payment_.py
art_show/configspec.ini
art_show/models.py
art_show/site_sections/art_show_admin.py
art_show/templates/art_pieces_form.html
art_show/templates/art_show_admin/bidder_signup.html
art_show/templates/art_show_admin/form.html
art_show/templates/art_show_admin/ops.html
art_show/templates/art_show_admin/pieces_bought.html
art_show/templates/art_show_admin/print_receipt.html
art_show/templates/art_show_admin/sales_search.html
art_show/templates/artist_checkin_macros.html
art_show/templates/emails/art_show/appchange_notification.html
art_show/templates/emails/art_show/pieces_confirmation.html
art_show/templates/print_form.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/121. Fixes https://github.com/MidwestFurryFandom/art_show/issues/122. We use just one workflow for sales, which should hopefully be very efficient for both bid sales and quick sales.
This was a pretty big feature but it was all very interdependent -- I had to change the models to support multiple receipts midway through. 😰

Add sales page for quick sales and bid sales

---

art_show/models.py
art_show/site_sections/art_show_admin.py

I have no idea why 3of9 barcodes need asterisks on either side of the data, but they do!

Encase 3of9 barcode data in asterisks like we're supposed to

---

art_show/templates/art_pieces_form.html
art_show/templates/art_show_admin/artist_check_in_out.html
art_show/templates/art_show_admin/ops.html
art_show/templates/art_show_reports/index.html
art_show/templates/artist_checkin_macros.html
art_show/templates/print_form.html

For unknown reasons, running regionChange() on page load was not actually changing the dropdown box inside the artist check-in model. This fixes that. We also do a bunch of clean-up to the address form to help output less HTML.
Requires https://github.com/MidwestFurryFandom/rams/pull/290.

Force address form state to refresh on artist check-in modals

---

art_show/configspec.ini
art_show/templates/art_show_admin/form.html

This is a dangerous feature because there is no adjusting done for payment and we will almost certainly regret this.
Let's do it!
NOTE: admins must manually adjust the 'amount paid' when changing the attendee.
NOTE2: this uses a new level of access called Art Show Admin so we can restrict it to just Directors and ADs.

Add ability for art show admins to change attendees on applications

---

alembic/versions/0a3de3158ae9_add_us_only_verification_for_mail_in_.py
art_show/configspec.ini
art_show/model_checks.py
art_show/models.py
art_show/site_sections/art_show_admin.py
art_show/templates/art_show_applications/art_show_form.html

Artists are required to check a box saying they will provide an address in the continental US. Requires a DB migration.

Add checkbox for mail-in artists verifying they will use a US address

---

alembic/versions/b55cbf903320_initial_migration.py

Not entirely sure this does anything, but we noticed while sorting out our database migrations that some of our plugin migrations had a file name different from their actual revision ID. Renaming it in case it affects alembic's version table.

Rename base migration

---

art_show/templates/art_pieces_form.html
art_show/templates/artist_checkin_macros.html
art_show/templates/print_form.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/199, hopefully. I wasn't able to reliably reproduce the issue, but I believe it came down to the use of our full combined CSS in the print form rather than just the bootstrap CSS we needed.
We also now print the check-in form from the check-in box the same way we print it from the pieces screen -- for some reason they had different implementations.

Standardize and improve printing of check-in form

---

art_show/site_sections/art_show_admin.py
art_show/templates/art_show_admin/pieces_bought.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/233. Admins can now click an X near each payment or refund line item to remove it, thus 'canceling' the payment.

Add ability to remove payments and refunds from sales

---

art_show/templates/artist_checkin_macros.html

Fixes https://github.com/MidwestFurryFandom/art_show/issues/245. Also fixes https://github.com/MidwestFurryFandom/art_show/issues/244 by adding sorting to the modal form.
I'm currently waiting on clarification for if different sorting on the _printed_ form is required or if it's just needed for the modal.

Add status column to printed check-in/out forms

---

art_show/site_sections/art_show_applications.py

New pieces couldn't be entered at all because a model check was trying to access the piece's application before it had one. Now it's fixed!

Fix 500 error when entering new pieces

---

art_show/site_sections/art_show_applications.py

I haven't the slightest idea how I didn't catch this during testing for the last PR; I must have forgotten to restart my local server after one of my changes. Not associating the piece with the app causes the general/mature check to fail -- not explicitly associating the app ID with the piece causes the duplicate name check to always pass. So we really do need both!

Add app AND app_id to piece before model checks

---

art_show/automated_emails.py

We actually want to send the mail-in instructions about a week before the dates it was set for, so we're updating its `when` property.

Update mail-in email date

---

art_show/site_sections/art_show_admin.py

Fixes https://github.com/MidwestFurryFandom/art_show/issues/276. We use a payment dropdown box on the app form, but the logic that kept it synchronized with the app status was accidentally forcing an approved application to ALWAYS be either approved or paid, even if you selected a different status.

Stop resetting any approved application to approved/paid

---

art_show/site_sections/art_show_admin.py

Fixes https://github.com/MidwestFurryFandom/art_show/issues/277. Based on the code, it does not seem we ever shrunk piece names on bid sheets.

Shrink font size for piece and artist names

---

art_show/site_sections/art_show_admin.py

We thought this worked because the page kept the values on reload, but it never actually saved to the DB. Now it saves.

Actually save artist locations

---

art_show/templates/art_show_admin/artist_check_in_out.html
art_show/templates/artist_checkin_macros.html
art_show/templates/print_macros.html

For some reason the onsite computers aren't opening two windows to print the two forms. We're quickly splitting the function into two buttons so art show can print both forms.

Split check-out printing into two buttons
